### ISSUE TITLE
Errors should be signaled, not only printed!

### ISSUE THREAD

**Issue by informatimago** [hamzashahid-blit/Claculator#1]
https://github.com/hamzashahid-blit/Claculator/blob/46a307a4e6443bac3fe3f8ae3b68d552ec237634/src/lexer.lisp#L22

Use at the very least te ERROR function:
```
(ERROR "Could not completely tokenize the stream ~S ; Unexpected char ~S" stream char)
```

Later, it may be interesting to define conditions for each class of error, so that handling them is easier (handler-case can dispatch on the condition class).

If you want to be able to continue upon error,  you may use CERROR instead of ERROR, or define and use restarts (which ease the automatic handling and continuation from the error).

**Comment by hamzashahid-blit** [comment]
On it Boss!

**Comment by hamzashahid-blit** [comment]
I have added this with the new commit 32fd504b3a3c3a69972534863e08f2040d92a87f.
Thanks PJB.
