### ISSUE TITLE
Add unit tests for each operator

### ISSUE THREAD

**Issue by informatimago** [hamzashahid-blit/Claculator#2]
Add unit tests for each operator.

Several tests may be required, to ensure 100% coverage, ie. that all the code is tested (all branches).

Note: to make unit tests of exceptional cases, it's often needed to "mock" auxiliary functions; the test system should allow it and make it easy.

**Comment by hamzashahid-blit** [comment]
Okay, I think I have 100% coverage for right now. If you don't think so, feel free to comment.
Thanks PJB.
Regards, Hamza Shahid.
