### ISSUE TITLE
move token-operator-p near the rest of the functional abstraction

### ISSUE THREAD

**Issue by informatimago** [hamzashahid-blit/Claculator#3]
Move this token-operator-p function
https://github.com/hamzashahid-blit/Claculator/blob/46a307a4e6443bac3fe3f8ae3b68d552ec237634/src/lexer.lisp#L3
near define-operators and operators-count. 
When you modify a functional abstraction, you should have to modify only one source file.

**Comment by hamzashahid-blit** [comment]
Done! Thanks PJB.
Regards, Hamza Shahid
